-- PoolPay Indian airports dimension (run in Supabase SQL Editor)
create table if not exists public.indian_airports (
  iata_code text primary key,
  city text not null,
  airport_name text not null,
  state text not null,
  label text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.indian_airports enable row level security;

drop policy if exists "Anyone can read active indian airports" on public.indian_airports;
create policy "Anyone can read active indian airports"
  on public.indian_airports for select
  using (is_active = true);

insert into public.indian_airports (iata_code, city, airport_name, state, label) values
  ('DEL', 'New Delhi', 'Indira Gandhi International', 'Delhi', 'New Delhi (DEL)'),
  ('BOM', 'Mumbai', 'Chhatrapati Shivaji Maharaj International', 'Maharashtra', 'Mumbai (BOM)'),
  ('BLR', 'Bengaluru', 'Kempegowda International', 'Karnataka', 'Bengaluru (BLR)'),
  ('HYD', 'Hyderabad', 'Rajiv Gandhi International', 'Telangana', 'Hyderabad (HYD)'),
  ('MAA', 'Chennai', 'Chennai International', 'Tamil Nadu', 'Chennai (MAA)'),
  ('CCU', 'Kolkata', 'Netaji Subhas Chandra Bose International', 'West Bengal', 'Kolkata (CCU)'),
  ('GOI', 'Goa', 'Manohar International', 'Goa', 'Goa (GOI)'),
  ('GOX', 'Goa', 'Dabolim International', 'Goa', 'Goa Dabolim (GOX)'),
  ('PNQ', 'Pune', 'Pune International', 'Maharashtra', 'Pune (PNQ)'),
  ('AMD', 'Ahmedabad', 'Sardar Vallabhbhai Patel International', 'Gujarat', 'Ahmedabad (AMD)'),
  ('COK', 'Kochi', 'Cochin International', 'Kerala', 'Kochi (COK)'),
  ('TRV', 'Thiruvananthapuram', 'Trivandrum International', 'Kerala', 'Thiruvananthapuram (TRV)'),
  ('CCJ', 'Kozhikode', 'Calicut International', 'Kerala', 'Kozhikode (CCJ)'),
  ('CNN', 'Kannur', 'Kannur International', 'Kerala', 'Kannur (CNN)'),
  ('JAI', 'Jaipur', 'Jaipur International', 'Rajasthan', 'Jaipur (JAI)'),
  ('UDR', 'Udaipur', 'Maharana Pratap', 'Rajasthan', 'Udaipur (UDR)'),
  ('JDH', 'Jodhpur', 'Jodhpur', 'Rajasthan', 'Jodhpur (JDH)'),
  ('LKO', 'Lucknow', 'Chaudhary Charan Singh International', 'Uttar Pradesh', 'Lucknow (LKO)'),
  ('VNS', 'Varanasi', 'Lal Bahadur Shastri International', 'Uttar Pradesh', 'Varanasi (VNS)'),
  ('AGR', 'Agra', 'Agra', 'Uttar Pradesh', 'Agra (AGR)'),
  ('IXC', 'Chandigarh', 'Chandigarh International', 'Chandigarh', 'Chandigarh (IXC)'),
  ('ATQ', 'Amritsar', 'Sri Guru Ram Dass Jee International', 'Punjab', 'Amritsar (ATQ)'),
  ('IXJ', 'Jammu', 'Jammu', 'Jammu and Kashmir', 'Jammu (IXJ)'),
  ('SXR', 'Srinagar', 'Sheikh ul-Alam International', 'Jammu and Kashmir', 'Srinagar (SXR)'),
  ('IXL', 'Leh', 'Kushok Bakula Rimpochee', 'Ladakh', 'Leh (IXL)'),
  ('DED', 'Dehradun', 'Jolly Grant', 'Uttarakhand', 'Dehradun (DED)'),
  ('GAU', 'Guwahati', 'Lokpriya Gopinath Bordoloi International', 'Assam', 'Guwahati (GAU)'),
  ('IXB', 'Bagdogra', 'Bagdogra', 'West Bengal', 'Bagdogra (IXB)'),
  ('IXR', 'Ranchi', 'Birsa Munda', 'Jharkhand', 'Ranchi (IXR)'),
  ('PAT', 'Patna', 'Jay Prakash Narayan International', 'Bihar', 'Patna (PAT)'),
  ('GAY', 'Gaya', 'Gaya', 'Bihar', 'Gaya (GAY)'),
  ('BBI', 'Bhubaneswar', 'Biju Patnaik International', 'Odisha', 'Bhubaneswar (BBI)'),
  ('VTZ', 'Visakhapatnam', 'Visakhapatnam', 'Andhra Pradesh', 'Visakhapatnam (VTZ)'),
  ('RJA', 'Rajahmundry', 'Rajahmundry', 'Andhra Pradesh', 'Rajahmundry (RJA)'),
  ('TIR', 'Tirupati', 'Tirupati', 'Andhra Pradesh', 'Tirupati (TIR)'),
  ('VGA', 'Vijayawada', 'Vijayawada', 'Andhra Pradesh', 'Vijayawada (VGA)'),
  ('IXZ', 'Port Blair', 'Veer Savarkar International', 'Andaman and Nicobar', 'Port Blair (IXZ)'),
  ('NAG', 'Nagpur', 'Dr. Babasaheb Ambedkar International', 'Maharashtra', 'Nagpur (NAG)'),
  ('IDR', 'Indore', 'Devi Ahilya Bai Holkar', 'Madhya Pradesh', 'Indore (IDR)'),
  ('BHO', 'Bhopal', 'Raja Bhoj', 'Madhya Pradesh', 'Bhopal (BHO)'),
  ('JLR', 'Jabalpur', 'Jabalpur', 'Madhya Pradesh', 'Jabalpur (JLR)'),
  ('RPR', 'Raipur', 'Swami Vivekananda', 'Chhattisgarh', 'Raipur (RPR)'),
  ('IXE', 'Mangaluru', 'Mangalore International', 'Karnataka', 'Mangaluru (IXE)'),
  ('HBX', 'Hubballi', 'Hubballi', 'Karnataka', 'Hubballi (HBX)'),
  ('IXG', 'Belagavi', 'Belagavi', 'Karnataka', 'Belagavi (IXG)'),
  ('MYQ', 'Mysuru', 'Mysuru', 'Karnataka', 'Mysuru (MYQ)'),
  ('BDQ', 'Vadodara', 'Vadodara', 'Gujarat', 'Vadodara (BDQ)'),
  ('STV', 'Surat', 'Surat', 'Gujarat', 'Surat (STV)'),
  ('RAJ', 'Rajkot', 'Rajkot', 'Gujarat', 'Rajkot (RAJ)'),
  ('BHU', 'Bhavnagar', 'Bhavnagar', 'Gujarat', 'Bhavnagar (BHU)'),
  ('IXU', 'Aurangabad', 'Aurangabad', 'Maharashtra', 'Aurangabad (IXU)'),
  ('NMI', 'Nashik', 'Nashik', 'Maharashtra', 'Nashik (NMI)'),
  ('KLH', 'Kolhapur', 'Kolhapur', 'Maharashtra', 'Kolhapur (KLH)'),
  ('IXM', 'Madurai', 'Madurai', 'Tamil Nadu', 'Madurai (IXM)'),
  ('TRZ', 'Tiruchirappalli', 'Tiruchirappalli International', 'Tamil Nadu', 'Tiruchirappalli (TRZ)'),
  ('CJB', 'Coimbatore', 'Coimbatore International', 'Tamil Nadu', 'Coimbatore (CJB)'),
  ('SXV', 'Salem', 'Salem', 'Tamil Nadu', 'Salem (SXV)'),
  ('TCR', 'Tuticorin', 'Tuticorin', 'Tamil Nadu', 'Tuticorin (TCR)'),
  ('IMF', 'Imphal', 'Imphal', 'Manipur', 'Imphal (IMF)'),
  ('AJL', 'Aizawl', 'Lengpui', 'Mizoram', 'Aizawl (AJL)'),
  ('SHL', 'Shillong', 'Shillong', 'Meghalaya', 'Shillong (SHL)'),
  ('DMU', 'Dimapur', 'Dimapur', 'Nagaland', 'Dimapur (DMU)'),
  ('IXA', 'Agartala', 'Maharaja Bir Bikram', 'Tripura', 'Agartala (IXA)'),
  ('DIB', 'Dibrugarh', 'Dibrugarh', 'Assam', 'Dibrugarh (DIB)'),
  ('IXS', 'Silchar', 'Silchar', 'Assam', 'Silchar (IXS)'),
  ('TEZ', 'Tezpur', 'Tezpur', 'Assam', 'Tezpur (TEZ)'),
  ('JRH', 'Jorhat', 'Jorhat', 'Assam', 'Jorhat (JRH)'),
  ('IXD', 'Allahabad', 'Prayagraj', 'Uttar Pradesh', 'Prayagraj (IXD)'),
  ('GOP', 'Gorakhpur', 'Gorakhpur', 'Uttar Pradesh', 'Gorakhpur (GOP)'),
  ('KNU', 'Kanpur', 'Kanpur', 'Uttar Pradesh', 'Kanpur (KNU)'),
  ('IXW', 'Jamshedpur', 'Sonari', 'Jharkhand', 'Jamshedpur (IXW)'),
  ('DBR', 'Darbhanga', 'Darbhanga', 'Bihar', 'Darbhanga (DBR)'),
  ('IXI', 'Lilabari', 'Lilabari', 'Assam', 'Lilabari (IXI)'),
  ('SLV', 'Shimla', 'Shimla', 'Himachal Pradesh', 'Shimla (SLV)'),
  ('KUU', 'Kullu', 'Bhuntar', 'Himachal Pradesh', 'Kullu (KUU)'),
  ('DHM', 'Dharamshala', 'Gaggal', 'Himachal Pradesh', 'Dharamshala (DHM)'),
  ('PGH', 'Pantnagar', 'Pantnagar', 'Uttarakhand', 'Pantnagar (PGH)'),
  ('DIU', 'Diu', 'Diu', 'Daman and Diu', 'Diu (DIU)'),
  ('ISK', 'Nashik', 'Ozar', 'Maharashtra', 'Nashik Ozar (ISK)'),
  ('SAG', 'Shirdi', 'Shirdi', 'Maharashtra', 'Shirdi (SAG)'),
  ('JGA', 'Jamnagar', 'Jamnagar', 'Gujarat', 'Jamnagar (JGA)'),
  ('BKB', 'Bikaner', 'Nal', 'Rajasthan', 'Bikaner (BKB)'),
  ('KQH', 'Kishangarh', 'Kishangarh', 'Rajasthan', 'Kishangarh (KQH)'),
  ('HSR', 'Rajkot', 'Hirasar', 'Gujarat', 'Rajkot Hirasar (HSR)'),
  ('PYG', 'Gangtok', 'Pakyong', 'Sikkim', 'Gangtok (PYG)'),
  ('IXH', 'Kailashahar', 'Kailashahar', 'Tripura', 'Kailashahar (IXH)'),
  ('RDP', 'Durgapur', 'Kazi Nazrul Islam', 'West Bengal', 'Durgapur (RDP)'),
  ('CDP', 'Kadapa', 'Kadapa', 'Andhra Pradesh', 'Kadapa (CDP)'),
  ('PUT', 'Puttaparthi', 'Sri Sathya Sai', 'Andhra Pradesh', 'Puttaparthi (PUT)'),
  ('BEP', 'Bellary', 'Ballari', 'Karnataka', 'Bellary (BEP)'),
  ('VDY', 'Vidyanagar', 'Jindal Vijaynagar', 'Karnataka', 'Vidyanagar (VDY)'),
  ('BUP', 'Bathinda', 'Bathinda', 'Punjab', 'Bathinda (BUP)'),
  ('LUH', 'Ludhiana', 'Ludhiana', 'Punjab', 'Ludhiana (LUH)'),
  ('DHN', 'Dhanbad', 'Dhanbad', 'Jharkhand', 'Dhanbad (DHN)'),
  ('BHJ', 'Bhuj', 'Bhuj', 'Gujarat', 'Bhuj (BHJ)'),
  ('JGB', 'Jagdalpur', 'Jagdalpur', 'Chhattisgarh', 'Jagdalpur (JGB)'),
  ('JSA', 'Jaisalmer', 'Jaisalmer', 'Rajasthan', 'Jaisalmer (JSA)'),
  ('HGI', 'Itanagar', 'Hollongi', 'Arunachal Pradesh', 'Itanagar (HGI)'),
  ('TEI', 'Tezu', 'Tezu', 'Arunachal Pradesh', 'Tezu (TEI)'),
  ('ZER', 'Ziro', 'Ziro', 'Arunachal Pradesh', 'Ziro (ZER)'),
  ('PBD', 'Porbandar', 'Porbandar', 'Gujarat', 'Porbandar (PBD)'),
  ('IXY', 'Kandla', 'Kandla', 'Gujarat', 'Kandla (IXY)'),
  ('IXK', 'Keshod', 'Keshod', 'Gujarat', 'Keshod (IXK)')
on conflict (iata_code) do update set
  city = excluded.city,
  airport_name = excluded.airport_name,
  state = excluded.state,
  label = excluded.label,
  is_active = true;
