/** AUTO-GENERATED — run: node scripts/generate-card-catalog-master.mjs */
import { BANK_REGISTRY } from "@/lib/bank-registry"
import { resolveCardImageUrl } from "@/lib/card-photo-registry"

export type CatalogCard = {
  card_id: string
  bank_id: string
  bank_name: string
  bank_logo_url?: string
  card_name: string
  card_image_url?: string
  style_classes: string
  apply_url: string
}

const logo = (bankId: string) =>
  BANK_REGISTRY.find((b) => b.bank_id === bankId)?.logo_url ?? "/banks/default.svg"

const RAW: Omit<CatalogCard, "bank_logo_url">[] = [
  {
    card_id: "hdfc_infinia",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "HDFC Infinia Metal",
    card_image_url: "/cards/hdfc_infinia.svg",
    style_classes: "bg-gradient-to-br from-slate-900 to-black text-slate-200",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_diners_black",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "HDFC Diners Club Black",
    card_image_url: "/cards/hdfc_diners_black.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-zinc-300",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_regalia_gold",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "HDFC Regalia Gold",
    card_image_url: "/cards/hdfc_regalia_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-600 to-yellow-800 text-yellow-50",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_millennia",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "HDFC Millennia",
    card_image_url: "/cards/hdfc_millennia.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-blue-100",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_tata_neu_infinity",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "Tata Neu Infinity HDFC",
    card_image_url: "/cards/hdfc_tata_neu_infinity.svg",
    style_classes: "bg-gradient-to-br from-purple-900 to-violet-950 text-purple-100",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_tata_neu_plus",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "Tata Neu Plus HDFC",
    card_image_url: "/cards/hdfc_tata_neu_plus.svg",
    style_classes: "bg-gradient-to-br from-indigo-900 to-blue-950 text-indigo-100",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_swiggy",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "Swiggy HDFC",
    card_image_url: "/cards/hdfc_swiggy.svg",
    style_classes: "bg-gradient-to-br from-orange-500 to-black text-orange-50",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_moneyback_plus",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "HDFC MoneyBack+",
    card_image_url: "/cards/hdfc_moneyback_plus.svg",
    style_classes: "bg-gradient-to-br from-slate-700 to-slate-900 text-slate-100",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_indianoil",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "IndianOil HDFC",
    card_image_url: "/cards/hdfc_indianoil.svg",
    style_classes: "bg-gradient-to-br from-orange-600 to-orange-800 text-orange-50",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "hdfc_freedom",
    bank_id: "hdfc",
    bank_name: "HDFC",
    card_name: "HDFC Freedom",
    card_image_url: "/cards/hdfc_freedom.svg",
    style_classes: "bg-gradient-to-br from-sky-600 to-blue-800 text-sky-50",
    apply_url: "https://www.hdfc.bank.in/credit-cards",
  },
  {
    card_id: "icici_emeralde_private",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "ICICI Emeralde Private",
    card_image_url: "/cards/icici_emeralde_private.svg",
    style_classes: "bg-gradient-to-br from-emerald-900 to-green-950 text-emerald-100",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_sapphiro",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "ICICI Sapphiro",
    card_image_url: "/cards/icici_sapphiro.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-indigo-950 text-blue-100",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_rubyx",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "ICICI Rubyx",
    card_image_url: "/cards/icici_rubyx.svg",
    style_classes: "bg-gradient-to-br from-rose-800 to-red-950 text-rose-100",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_coral",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "ICICI Coral",
    card_image_url: "/cards/icici_coral.svg",
    style_classes: "bg-gradient-to-br from-rose-500 to-pink-800 text-rose-50",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_amazon_pay",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "Amazon Pay ICICI",
    card_image_url: "/cards/icici_amazon_pay.svg",
    style_classes: "bg-gradient-to-br from-orange-600 to-red-900 text-orange-50",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_mmt_signature",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "MakeMyTrip ICICI Signature",
    card_image_url: "/cards/icici_mmt_signature.svg",
    style_classes: "bg-gradient-to-br from-zinc-900 to-black text-zinc-200",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_mmt_platinum",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "MakeMyTrip ICICI Platinum",
    card_image_url: "/cards/icici_mmt_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_adani_signature",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "Adani One ICICI Signature",
    card_image_url: "/cards/icici_adani_signature.svg",
    style_classes: "bg-gradient-to-br from-black to-yellow-900 text-yellow-500",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_hpcl_super_saver",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "ICICI HPCL Super Saver",
    card_image_url: "/cards/icici_hpcl_super_saver.svg",
    style_classes: "bg-gradient-to-br from-red-600 to-blue-900 text-red-50",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "icici_man_utd",
    bank_id: "icici",
    bank_name: "ICICI",
    card_name: "ICICI Manchester United",
    card_image_url: "/cards/icici_man_utd.svg",
    style_classes: "bg-gradient-to-br from-red-700 to-red-900 text-red-50",
    apply_url: "https://www.icicibank.com/personal-banking/cards/credit-card",
  },
  {
    card_id: "sbi_aurum",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "SBI Card Aurum",
    card_image_url: "/cards/sbi_aurum.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-800 text-amber-500",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_elite",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "SBI Card Elite",
    card_image_url: "/cards/sbi_elite.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-amber-400",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_cashback",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "Cashback SBI Card",
    card_image_url: "/cards/sbi_cashback.svg",
    style_classes: "bg-gradient-to-br from-cyan-600 to-blue-900 text-cyan-50",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_simplyclick",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "SimplyCLICK SBI Card",
    card_image_url: "/cards/sbi_simplyclick.svg",
    style_classes: "bg-gradient-to-br from-sky-600 to-blue-700 text-sky-50",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_simplysave",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "SimplySAVE SBI Card",
    card_image_url: "/cards/sbi_simplysave.svg",
    style_classes: "bg-gradient-to-br from-amber-600 to-amber-900 text-amber-50",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_prime",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "SBI Card PRIME",
    card_image_url: "/cards/sbi_prime.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-950 text-blue-100",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_pulse",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "SBI Card PULSE",
    card_image_url: "/cards/sbi_pulse.svg",
    style_classes: "bg-gradient-to-br from-purple-800 to-fuchsia-950 text-purple-100",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_bpcl_octane",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "BPCL SBI Card OCTANE",
    card_image_url: "/cards/sbi_bpcl_octane.svg",
    style_classes: "bg-gradient-to-br from-slate-700 to-slate-900 text-green-400",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_club_vistara_prime",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "Club Vistara SBI Card PRIME",
    card_image_url: "/cards/sbi_club_vistara_prime.svg",
    style_classes: "bg-gradient-to-br from-indigo-900 to-violet-950 text-amber-500",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "sbi_reliance_prime",
    bank_id: "sbi",
    bank_name: "SBI",
    card_name: "Reliance SBI Card PRIME",
    card_image_url: "/cards/sbi_reliance_prime.svg",
    style_classes: "bg-gradient-to-br from-red-600 to-red-900 text-red-50",
    apply_url: "https://www.sbicard.com/en/personal/credit-cards",
  },
  {
    card_id: "axis_reserve",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank Reserve",
    card_image_url: "/cards/axis_reserve.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-yellow-500",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_magnus",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank Magnus",
    card_image_url: "/cards/axis_magnus.svg",
    style_classes: "bg-gradient-to-br from-red-900 to-rose-950 text-red-100",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_atlas",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank ATLAS",
    card_image_url: "/cards/axis_atlas.svg",
    style_classes: "bg-gradient-to-br from-slate-500 to-slate-800 text-slate-100",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_flipkart",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Flipkart Axis Bank",
    card_image_url: "/cards/axis_flipkart.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-yellow-400",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_ace",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank ACE",
    card_image_url: "/cards/axis_ace.svg",
    style_classes: "bg-gradient-to-br from-teal-500 to-teal-800 text-teal-50",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_airtel",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Airtel Axis Bank",
    card_image_url: "/cards/axis_airtel.svg",
    style_classes: "bg-gradient-to-br from-rose-600 to-black text-rose-50",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_neo",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank Neo",
    card_image_url: "/cards/axis_neo.svg",
    style_classes: "bg-gradient-to-br from-indigo-600 to-purple-800 text-indigo-50",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_my_zone",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank MY ZONE",
    card_image_url: "/cards/axis_my_zone.svg",
    style_classes: "bg-gradient-to-br from-gray-700 to-black text-red-500",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_vistara_infinite",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank Vistara Infinite",
    card_image_url: "/cards/axis_vistara_infinite.svg",
    style_classes: "bg-gradient-to-br from-violet-800 to-violet-950 text-yellow-500",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "axis_select",
    bank_id: "axis",
    bank_name: "AXIS",
    card_name: "Axis Bank SELECT",
    card_image_url: "/cards/axis_select.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.axis.bank.in/cards/credit-card",
  },
  {
    card_id: "kotak_white_reserve",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak White Reserve",
    card_image_url: "/cards/kotak_white_reserve.svg",
    style_classes: "bg-gradient-to-br from-slate-50 to-slate-200 text-slate-800",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_zen_signature",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak Zen Signature",
    card_image_url: "/cards/kotak_zen_signature.svg",
    style_classes: "bg-gradient-to-br from-gray-700 to-gray-900 text-gray-100",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_privy_league",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak Privy League Signature",
    card_image_url: "/cards/kotak_privy_league.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-indigo-950 text-yellow-500",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_royale_signature",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak Royale Signature",
    card_image_url: "/cards/kotak_royale_signature.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-900 text-yellow-400",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_league_platinum",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak League Platinum",
    card_image_url: "/cards/kotak_league_platinum.svg",
    style_classes: "bg-gradient-to-br from-red-600 to-red-800 text-red-50",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_mojo_platinum",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak Mojo Platinum",
    card_image_url: "/cards/kotak_mojo_platinum.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-800 text-yellow-500",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_811",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak 811 #DreamDifferent",
    card_image_url: "/cards/kotak_811.svg",
    style_classes: "bg-gradient-to-br from-red-700 to-red-900 text-white",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_pvr_platinum",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak PVR Platinum",
    card_image_url: "/cards/kotak_pvr_platinum.svg",
    style_classes: "bg-gradient-to-br from-gray-800 to-black text-yellow-500",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_indianoil",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "IndianOil Kotak",
    card_image_url: "/cards/kotak_indianoil.svg",
    style_classes: "bg-gradient-to-br from-orange-500 to-orange-700 text-orange-50",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "kotak_myntra",
    bank_id: "kotak",
    bank_name: "KOTAK",
    card_name: "Kotak Myntra",
    card_image_url: "/cards/kotak_myntra.svg",
    style_classes: "bg-gradient-to-br from-pink-600 to-purple-700 text-pink-50",
    apply_url: "https://www.kotak.com/en/personal-banking/cards/credit-cards.html",
  },
  {
    card_id: "idfc_private",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Private",
    card_image_url: "/cards/idfc_private.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-zinc-300",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_mayura",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Mayura",
    card_image_url: "/cards/idfc_mayura.svg",
    style_classes: "bg-gradient-to-br from-teal-700 to-teal-950 text-amber-400",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_ashva",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Ashva",
    card_image_url: "/cards/idfc_ashva.svg",
    style_classes: "bg-gradient-to-br from-amber-800 to-amber-950 text-amber-200",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_wealth",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Wealth",
    card_image_url: "/cards/idfc_wealth.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-blue-100",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_select",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Select",
    card_image_url: "/cards/idfc_select.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_millennia",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Millennia",
    card_image_url: "/cards/idfc_millennia.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-blue-50",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_classic",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Classic",
    card_image_url: "/cards/idfc_classic.svg",
    style_classes: "bg-gradient-to-br from-red-800 to-red-950 text-red-50",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_wow",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST WOW!",
    card_image_url: "/cards/idfc_wow.svg",
    style_classes: "bg-gradient-to-br from-gray-600 to-gray-800 text-gray-100",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_power_plus",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "FIRST Power+",
    card_image_url: "/cards/idfc_power_plus.svg",
    style_classes: "bg-gradient-to-br from-red-700 to-red-900 text-red-50",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "idfc_indigo",
    bank_id: "idfc",
    bank_name: "IDFC",
    card_name: "IndiGo IDFC FIRST",
    card_image_url: "/cards/idfc_indigo.svg",
    style_classes: "bg-gradient-to-br from-indigo-600 to-indigo-900 text-indigo-50",
    apply_url: "https://www.idfcfirstbank.com/credit-card",
  },
  {
    card_id: "indusind_legend",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Legend",
    card_image_url: "/cards/indusind_legend.svg",
    style_classes: "bg-gradient-to-br from-red-900 to-orange-950 text-red-100",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_pinnacle",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Pinnacle",
    card_image_url: "/cards/indusind_pinnacle.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-yellow-500",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_aura_edge",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Aura Edge",
    card_image_url: "/cards/indusind_aura_edge.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-slate-200",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_platinum_aura",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Platinum Aura",
    card_image_url: "/cards/indusind_platinum_aura.svg",
    style_classes: "bg-gradient-to-br from-slate-300 to-slate-500 text-slate-900",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_iconia",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Iconia",
    card_image_url: "/cards/indusind_iconia.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-slate-800 text-blue-100",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_nexxt",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Nexxt",
    card_image_url: "/cards/indusind_nexxt.svg",
    style_classes: "bg-gradient-to-br from-zinc-800 to-black text-cyan-400",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_eazydiner",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "EazyDiner IndusInd Bank",
    card_image_url: "/cards/indusind_eazydiner.svg",
    style_classes: "bg-gradient-to-br from-amber-600 to-stone-900 text-amber-50",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_club_vistara",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "Club Vistara IndusInd Bank",
    card_image_url: "/cards/indusind_club_vistara.svg",
    style_classes: "bg-gradient-to-br from-violet-800 to-violet-950 text-yellow-500",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_tiger",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Tiger",
    card_image_url: "/cards/indusind_tiger.svg",
    style_classes: "bg-gradient-to-br from-orange-600 to-orange-900 text-orange-50",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "indusind_crest",
    bank_id: "indusind",
    bank_name: "INDUSIND",
    card_name: "IndusInd Bank Crest",
    card_image_url: "/cards/indusind_crest.svg",
    style_classes: "bg-gradient-to-br from-slate-800 to-slate-950 text-yellow-400",
    apply_url: "https://www.indusind.com/in/en/personal/cards/credit-cards.html",
  },
  {
    card_id: "pnb_rupay_select",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB RuPay Select",
    card_image_url: "/cards/pnb_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-sky-700 to-blue-900 text-sky-100",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_rupay_platinum",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB RuPay Platinum",
    card_image_url: "/cards/pnb_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-700 to-slate-900 text-slate-100",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_visa_signature",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB Visa Signature",
    card_image_url: "/cards/pnb_visa_signature.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-950 text-blue-50",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_visa_platinum",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB Visa Platinum",
    card_image_url: "/cards/pnb_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_rupay_millennial",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB RuPay Millennial",
    card_image_url: "/cards/pnb_rupay_millennial.svg",
    style_classes: "bg-gradient-to-br from-indigo-600 to-purple-800 text-indigo-50",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_wave",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB Wave",
    card_image_url: "/cards/pnb_wave.svg",
    style_classes: "bg-gradient-to-br from-cyan-600 to-blue-800 text-cyan-50",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_rakshak",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB Rakshak RuPay Select",
    card_image_url: "/cards/pnb_rakshak.svg",
    style_classes: "bg-gradient-to-br from-lime-700 to-green-900 text-lime-50",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_patanjali_platinum",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB Patanjali RuPay Platinum",
    card_image_url: "/cards/pnb_patanjali_platinum.svg",
    style_classes: "bg-gradient-to-br from-green-700 to-green-900 text-green-50",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_global_gold",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB Global Gold",
    card_image_url: "/cards/pnb_global_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-600 to-amber-800 text-yellow-50",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "pnb_global_classic",
    bank_id: "pnb",
    bank_name: "PNB",
    card_name: "PNB Global Classic",
    card_image_url: "/cards/pnb_global_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-blue-50",
    apply_url: "https://www.pnbindia.in/credit-card.html",
  },
  {
    card_id: "bob_eterna",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Eterna",
    card_image_url: "/cards/bob_eterna.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-yellow-500",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_premier",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Premier",
    card_image_url: "/cards/bob_premier.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_select",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Select",
    card_image_url: "/cards/bob_select.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-900 text-blue-50",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_easy",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Easy",
    card_image_url: "/cards/bob_easy.svg",
    style_classes: "bg-gradient-to-br from-amber-500 to-orange-600 text-amber-50",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_hpcl_energie",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB HPCL Energie",
    card_image_url: "/cards/bob_hpcl_energie.svg",
    style_classes: "bg-gradient-to-br from-red-600 to-blue-800 text-red-50",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_irctc",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB IRCTC",
    card_image_url: "/cards/bob_irctc.svg",
    style_classes: "bg-gradient-to-br from-sky-600 to-blue-800 text-sky-50",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_snapdeal",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Snapdeal",
    card_image_url: "/cards/bob_snapdeal.svg",
    style_classes: "bg-gradient-to-br from-rose-600 to-red-800 text-rose-50",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_yoddha",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Yoddha",
    card_image_url: "/cards/bob_yoddha.svg",
    style_classes: "bg-gradient-to-br from-green-700 to-green-900 text-green-50",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_varunah",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Varunah Plus",
    card_image_url: "/cards/bob_varunah.svg",
    style_classes: "bg-gradient-to-br from-slate-800 to-blue-950 text-blue-100",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "bob_pragati",
    bank_id: "bob",
    bank_name: "BOB",
    card_name: "BOB Pragati",
    card_image_url: "/cards/bob_pragati.svg",
    style_classes: "bg-gradient-to-br from-emerald-600 to-green-800 text-emerald-50",
    apply_url: "https://www.bobfinancial.com/credit-card",
  },
  {
    card_id: "canara_visa_signature",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara Visa Signature",
    card_image_url: "/cards/canara_visa_signature.svg",
    style_classes: "bg-gradient-to-br from-slate-800 to-black text-slate-200",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_rupay_select",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara RuPay Select",
    card_image_url: "/cards/canara_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-sky-700 to-blue-900 text-sky-50",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_mastercard_world",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara Mastercard World",
    card_image_url: "/cards/canara_mastercard_world.svg",
    style_classes: "bg-gradient-to-br from-zinc-800 to-black text-zinc-300",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_visa_platinum",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara Visa Platinum",
    card_image_url: "/cards/canara_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_rupay_platinum",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara RuPay Platinum",
    card_image_url: "/cards/canara_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-blue-50",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_mastercard_platinum",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara Mastercard Platinum",
    card_image_url: "/cards/canara_mastercard_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-slate-800 text-slate-100",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_visa_classic",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara Visa Classic",
    card_image_url: "/cards/canara_visa_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-500 to-blue-700 text-blue-50",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_rupay_classic",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara RuPay Classic",
    card_image_url: "/cards/canara_rupay_classic.svg",
    style_classes: "bg-gradient-to-br from-emerald-600 to-teal-800 text-emerald-50",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_mastercard_classic",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara Mastercard Classic",
    card_image_url: "/cards/canara_mastercard_classic.svg",
    style_classes: "bg-gradient-to-br from-sky-500 to-blue-700 text-sky-50",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "canara_corporate",
    bank_id: "canara",
    bank_name: "CANARA",
    card_name: "Canara Corporate",
    card_image_url: "/cards/canara_corporate.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-slate-900 text-yellow-500",
    apply_url: "https://www.canarabank.com/credit-card",
  },
  {
    card_id: "union_uni_carbon",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank Uni Carbon",
    card_image_url: "/cards/union_uni_carbon.svg",
    style_classes: "bg-gradient-to-br from-gray-700 to-green-900 text-green-100",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_signature",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank Signature",
    card_image_url: "/cards/union_signature.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-yellow-500",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_rupay_select",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank RuPay Select",
    card_image_url: "/cards/union_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-sky-700 to-blue-900 text-sky-50",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_jcb_premier",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank JCB Premier",
    card_image_url: "/cards/union_jcb_premier.svg",
    style_classes: "bg-gradient-to-br from-red-700 to-red-950 text-yellow-500",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_platinum",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank Platinum",
    card_image_url: "/cards/union_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_rupay_platinum",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank RuPay Platinum",
    card_image_url: "/cards/union_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-900 text-blue-50",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_usecure",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank Usecure",
    card_image_url: "/cards/union_usecure.svg",
    style_classes: "bg-gradient-to-br from-sky-500 to-sky-700 text-sky-50",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_gold",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank Gold",
    card_image_url: "/cards/union_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-500 to-amber-700 text-amber-50",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_disha",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank Disha",
    card_image_url: "/cards/union_disha.svg",
    style_classes: "bg-gradient-to-br from-green-600 to-green-800 text-green-50",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "union_classic",
    bank_id: "union",
    bank_name: "UNION",
    card_name: "Union Bank Classic",
    card_image_url: "/cards/union_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-500 to-blue-700 text-blue-50",
    apply_url: "https://www.unionbankofindia.co.in/english/creditcard.aspx",
  },
  {
    card_id: "boi_visa_signature",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI Visa Signature",
    card_image_url: "/cards/boi_visa_signature.svg",
    style_classes: "bg-gradient-to-br from-slate-800 to-black text-slate-200",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_rupay_select",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI RuPay Select",
    card_image_url: "/cards/boi_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-blue-950 text-blue-100",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_visa_platinum",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI Visa Platinum",
    card_image_url: "/cards/boi_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_rupay_platinum",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI RuPay Platinum",
    card_image_url: "/cards/boi_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-blue-900 text-slate-100",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_mastercard_platinum",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI Mastercard Platinum",
    card_image_url: "/cards/boi_mastercard_platinum.svg",
    style_classes: "bg-gradient-to-br from-gray-600 to-gray-800 text-gray-100",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_swadhaan",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI SwaDhaan RuPay",
    card_image_url: "/cards/boi_swadhaan.svg",
    style_classes: "bg-gradient-to-br from-orange-500 to-orange-700 text-orange-50",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_india_card",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI India Card",
    card_image_url: "/cards/boi_india_card.svg",
    style_classes: "bg-gradient-to-br from-slate-50 to-slate-200 text-slate-800",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_visa_gold",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI Visa Gold",
    card_image_url: "/cards/boi_visa_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-500 to-yellow-700 text-yellow-50",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_rupay_classic",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI RuPay Classic",
    card_image_url: "/cards/boi_rupay_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-blue-50",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "boi_sme",
    bank_id: "boi",
    bank_name: "BOI",
    card_name: "BOI SME Card",
    card_image_url: "/cards/boi_sme.svg",
    style_classes: "bg-gradient-to-br from-emerald-700 to-emerald-900 text-emerald-50",
    apply_url: "https://bankofindia.co.in/credit-card",
  },
  {
    card_id: "idbi_euphoria",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "IDBI Euphoria",
    card_image_url: "/cards/idbi_euphoria.svg",
    style_classes: "bg-gradient-to-br from-purple-800 to-indigo-950 text-purple-100",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_aspire",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "IDBI Aspire",
    card_image_url: "/cards/idbi_aspire.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_imperium",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "IDBI Imperium",
    card_image_url: "/cards/idbi_imperium.svg",
    style_classes: "bg-gradient-to-br from-amber-600 to-yellow-800 text-amber-50",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_winnings",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "IDBI Winnings RuPay Select",
    card_image_url: "/cards/idbi_winnings.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-900 text-blue-50",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_lic_signature",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "LIC IDBI Signature",
    card_image_url: "/cards/idbi_lic_signature.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-blue-950 text-yellow-500",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_lic_platinum",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "LIC IDBI Platinum",
    card_image_url: "/cards/idbi_lic_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-500 to-slate-700 text-slate-100",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_lic_titanium",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "LIC IDBI Titanium",
    card_image_url: "/cards/idbi_lic_titanium.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-slate-800 text-slate-200",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_lic_classic",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "LIC IDBI Classic",
    card_image_url: "/cards/idbi_lic_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-blue-50",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_rupay_select",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "IDBI RuPay Select",
    card_image_url: "/cards/idbi_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-sky-700 to-blue-900 text-sky-50",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "idbi_rupay_platinum",
    bank_id: "idbi",
    bank_name: "IDBI",
    card_name: "IDBI RuPay Platinum",
    card_image_url: "/cards/idbi_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-slate-800 text-slate-100",
    apply_url: "https://www.idbibank.in/credit-card.asp",
  },
  {
    card_id: "yes_marquee",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES Marquee",
    card_image_url: "/cards/yes_marquee.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-yellow-500",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_reserv",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES Reserv",
    card_image_url: "/cards/yes_reserv.svg",
    style_classes: "bg-gradient-to-br from-gray-300 to-gray-500 text-gray-900",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_first_exclusive",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES First Exclusive",
    card_image_url: "/cards/yes_first_exclusive.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-slate-200",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_first_preferred",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES First Preferred",
    card_image_url: "/cards/yes_first_preferred.svg",
    style_classes: "bg-gradient-to-br from-yellow-800 to-yellow-950 text-yellow-100",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_premia",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES Premia",
    card_image_url: "/cards/yes_premia.svg",
    style_classes: "bg-gradient-to-br from-teal-600 to-teal-800 text-teal-50",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_prosperity_rewards_plus",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES Prosperity Rewards Plus",
    card_image_url: "/cards/yes_prosperity_rewards_plus.svg",
    style_classes: "bg-gradient-to-br from-green-700 to-green-900 text-green-50",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_prosperity_edge",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES Prosperity Edge",
    card_image_url: "/cards/yes_prosperity_edge.svg",
    style_classes: "bg-gradient-to-br from-rose-800 to-rose-950 text-rose-100",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_finbooster",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "FinBooster YES Bank",
    card_image_url: "/cards/yes_finbooster.svg",
    style_classes: "bg-gradient-to-br from-orange-500 to-orange-700 text-orange-50",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_byoc",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES BYOC",
    card_image_url: "/cards/yes_byoc.svg",
    style_classes: "bg-gradient-to-br from-zinc-800 to-black text-cyan-400",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "yes_wellness_plus",
    bank_id: "yes",
    bank_name: "YES",
    card_name: "YES Wellness Plus",
    card_image_url: "/cards/yes_wellness_plus.svg",
    style_classes: "bg-gradient-to-br from-pink-700 to-pink-900 text-pink-50",
    apply_url: "https://www.yesbank.in/personal-banking/yes-individual/cards/credit-cards",
  },
  {
    card_id: "rbl_icon",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "RBL Bank Icon",
    card_image_url: "/cards/rbl_icon.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-blue-100",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "rbl_world_safari",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "RBL Bank World Safari",
    card_image_url: "/cards/rbl_world_safari.svg",
    style_classes: "bg-gradient-to-br from-amber-800 to-stone-900 text-amber-100",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "rbl_platinum_maxima",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "RBL Bank Platinum Maxima",
    card_image_url: "/cards/rbl_platinum_maxima.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-slate-800 text-slate-100",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "bajaj_rbl_platinum",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "Bajaj Finserv RBL Platinum",
    card_image_url: "/cards/bajaj_rbl_platinum.svg",
    style_classes: "bg-gradient-to-br from-sky-600 to-blue-800 text-sky-50",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "bajaj_rbl_binge",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "Bajaj Finserv RBL Binge",
    card_image_url: "/cards/bajaj_rbl_binge.svg",
    style_classes: "bg-gradient-to-br from-indigo-600 to-purple-800 text-indigo-50",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "rbl_shoprite",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "RBL Bank ShopRite",
    card_image_url: "/cards/rbl_shoprite.svg",
    style_classes: "bg-gradient-to-br from-green-600 to-green-800 text-green-50",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "rbl_play",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "RBL Bank Play",
    card_image_url: "/cards/rbl_play.svg",
    style_classes: "bg-gradient-to-br from-rose-600 to-red-800 text-rose-50",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "rbl_lazy_pay",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "LazyPay RBL Bank",
    card_image_url: "/cards/rbl_lazy_pay.svg",
    style_classes: "bg-gradient-to-br from-yellow-500 to-amber-600 text-yellow-50",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "rbl_cookies",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "RBL Bank Cookies",
    card_image_url: "/cards/rbl_cookies.svg",
    style_classes: "bg-gradient-to-br from-amber-600 to-orange-800 text-amber-50",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "rbl_savemax",
    bank_id: "rbl",
    bank_name: "RBL",
    card_name: "RBL Bank SaveMax",
    card_image_url: "/cards/rbl_savemax.svg",
    style_classes: "bg-gradient-to-br from-sky-500 to-cyan-700 text-sky-50",
    apply_url: "https://www.rblbank.com/personal-banking/cards/credit-cards",
  },
  {
    card_id: "hsbc_live_plus",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Live+",
    card_image_url: "/cards/hsbc_live_plus.svg",
    style_classes: "bg-gradient-to-br from-cyan-500 to-blue-700 text-cyan-50",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_premier",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Premier",
    card_image_url: "/cards/hsbc_premier.svg",
    style_classes: "bg-gradient-to-br from-gray-800 to-black text-slate-200",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_star_alliance",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Star Alliance",
    card_image_url: "/cards/hsbc_star_alliance.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-slate-100",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_visa_platinum",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Visa Platinum",
    card_image_url: "/cards/hsbc_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_smart_value",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Smart Value",
    card_image_url: "/cards/hsbc_smart_value.svg",
    style_classes: "bg-gradient-to-br from-red-600 to-red-800 text-red-50",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_cashback",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Cashback",
    card_image_url: "/cards/hsbc_cashback.svg",
    style_classes: "bg-gradient-to-br from-amber-500 to-orange-600 text-amber-50",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_premier_metal",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Premier Metal",
    card_image_url: "/cards/hsbc_premier_metal.svg",
    style_classes: "bg-gradient-to-br from-slate-700 to-zinc-900 text-slate-300",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_corporate",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Corporate",
    card_image_url: "/cards/hsbc_corporate.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-slate-900 text-blue-50",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_taj_epicure",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Taj Epicure",
    card_image_url: "/cards/hsbc_taj_epicure.svg",
    style_classes: "bg-gradient-to-br from-yellow-700 to-amber-900 text-yellow-50",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "hsbc_purchase_plus",
    bank_id: "hsbc",
    bank_name: "HSBC",
    card_name: "HSBC Purchase Plus",
    card_image_url: "/cards/hsbc_purchase_plus.svg",
    style_classes: "bg-gradient-to-br from-blue-500 to-blue-800 text-blue-50",
    apply_url: "https://www.hsbc.co.in/credit-cards/",
  },
  {
    card_id: "amex_platinum",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "American Express Platinum",
    card_image_url: "/cards/amex_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-300 to-slate-500 text-slate-900",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_gold",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "American Express Gold",
    card_image_url: "/cards/amex_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-400 to-yellow-600 text-yellow-950",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_mrcc",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex Membership Rewards (MRCC)",
    card_image_url: "/cards/amex_mrcc.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-blue-950 text-blue-100",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_smartearn",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex SmartEarn",
    card_image_url: "/cards/amex_smartearn.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-900 text-blue-50",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_platinum_travel",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex Platinum Travel",
    card_image_url: "/cards/amex_platinum_travel.svg",
    style_classes: "bg-gradient-to-br from-sky-500 to-blue-700 text-sky-50",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_platinum_reserve",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex Platinum Reserve",
    card_image_url: "/cards/amex_platinum_reserve.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-slate-800 text-slate-100",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_corporate_green",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex Corporate Green",
    card_image_url: "/cards/amex_corporate_green.svg",
    style_classes: "bg-gradient-to-br from-green-600 to-green-800 text-green-50",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_corporate_gold",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex Corporate Gold",
    card_image_url: "/cards/amex_corporate_gold.svg",
    style_classes: "bg-gradient-to-br from-amber-400 to-amber-600 text-amber-950",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_corporate_platinum",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex Corporate Platinum",
    card_image_url: "/cards/amex_corporate_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "amex_centurion",
    bank_id: "amex",
    bank_name: "AMEX",
    card_name: "Amex Centurion Black",
    card_image_url: "/cards/amex_centurion.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-zinc-300",
    apply_url: "https://www.americanexpress.com/in/credit-cards/",
  },
  {
    card_id: "sc_ultimate",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "Standard Chartered Ultimate",
    card_image_url: "/cards/sc_ultimate.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-slate-200",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_smart",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "Standard Chartered Smart",
    card_image_url: "/cards/sc_smart.svg",
    style_classes: "bg-gradient-to-br from-sky-600 to-blue-800 text-sky-50",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_platinum_rewards",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "SC Platinum Rewards",
    card_image_url: "/cards/sc_platinum_rewards.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-slate-900 text-blue-100",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_super_value_titanium",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "SC Super Value Titanium",
    card_image_url: "/cards/sc_super_value_titanium.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_easemytrip",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "EaseMyTrip Standard Chartered",
    card_image_url: "/cards/sc_easemytrip.svg",
    style_classes: "bg-gradient-to-br from-orange-500 to-orange-700 text-orange-50",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_manhattan",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "Standard Chartered Manhattan",
    card_image_url: "/cards/sc_manhattan.svg",
    style_classes: "bg-gradient-to-br from-green-600 to-green-800 text-green-50",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_digismart",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "Standard Chartered DigiSmart",
    card_image_url: "/cards/sc_digismart.svg",
    style_classes: "bg-gradient-to-br from-purple-600 to-purple-800 text-purple-50",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_priority_infinite",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "SC Priority Visa Infinite",
    card_image_url: "/cards/sc_priority_infinite.svg",
    style_classes: "bg-gradient-to-br from-slate-800 to-blue-950 text-yellow-500",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_renown",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "Standard Chartered Renown",
    card_image_url: "/cards/sc_renown.svg",
    style_classes: "bg-gradient-to-br from-red-800 to-red-950 text-red-50",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "sc_rewards",
    bank_id: "sc",
    bank_name: "SC",
    card_name: "Standard Chartered Rewards",
    card_image_url: "/cards/sc_rewards.svg",
    style_classes: "bg-gradient-to-br from-slate-500 to-slate-700 text-slate-100",
    apply_url: "https://www.sc.com/in/credit-cards/",
  },
  {
    card_id: "au_zenith",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU Zenith",
    card_image_url: "/cards/au_zenith.svg",
    style_classes: "bg-gradient-to-br from-black to-zinc-900 text-yellow-500",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_zenith_plus",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU Zenith+",
    card_image_url: "/cards/au_zenith_plus.svg",
    style_classes: "bg-gradient-to-br from-gray-800 to-black text-slate-300",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_vetta",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU Vetta",
    card_image_url: "/cards/au_vetta.svg",
    style_classes: "bg-gradient-to-br from-indigo-900 to-blue-950 text-indigo-100",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_altura",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU Altura",
    card_image_url: "/cards/au_altura.svg",
    style_classes: "bg-gradient-to-br from-teal-600 to-teal-800 text-teal-50",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_altura_plus",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU Altura+",
    card_image_url: "/cards/au_altura_plus.svg",
    style_classes: "bg-gradient-to-br from-rose-800 to-rose-950 text-rose-50",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_lit",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU LIT (Live It Today)",
    card_image_url: "/cards/au_lit.svg",
    style_classes: "bg-gradient-to-br from-amber-400 to-orange-500 text-zinc-900",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_ixigo",
    bank_id: "au",
    bank_name: "AU",
    card_name: "ixigo AU Credit Card",
    card_image_url: "/cards/au_ixigo.svg",
    style_classes: "bg-gradient-to-br from-sky-500 to-sky-700 text-orange-400",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_swipeup",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU SwipeUp",
    card_image_url: "/cards/au_swipeup.svg",
    style_classes: "bg-gradient-to-br from-violet-600 to-violet-800 text-violet-50",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_xcite",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU Xcite",
    card_image_url: "/cards/au_xcite.svg",
    style_classes: "bg-gradient-to-br from-cyan-500 to-blue-700 text-cyan-50",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "au_xcite_ultra",
    bank_id: "au",
    bank_name: "AU",
    card_name: "AU Xcite Ultra",
    card_image_url: "/cards/au_xcite_ultra.svg",
    style_classes: "bg-gradient-to-br from-green-700 to-green-900 text-green-50",
    apply_url: "https://www.aubank.in/personal-banking/credit-cards",
  },
  {
    card_id: "cbi_rupay_select",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank RuPay Select",
    card_image_url: "/cards/cbi_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-sky-700 to-blue-900 text-sky-50",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_rupay_platinum",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank RuPay Platinum",
    card_image_url: "/cards/cbi_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_visa_platinum",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank Visa Platinum",
    card_image_url: "/cards/cbi_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-900 text-blue-50",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_visa_gold",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank Visa Gold",
    card_image_url: "/cards/cbi_visa_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-500 to-yellow-700 text-yellow-50",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_mastercard_titanium",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank Mastercard Titanium",
    card_image_url: "/cards/cbi_mastercard_titanium.svg",
    style_classes: "bg-gradient-to-br from-slate-500 to-slate-700 text-slate-100",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_sbi_elite",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank SBI Card ELITE",
    card_image_url: "/cards/cbi_sbi_elite.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-black text-amber-400",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_sbi_prime",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank SBI Card PRIME",
    card_image_url: "/cards/cbi_sbi_prime.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-950 text-blue-100",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_simplysave_sbi",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "CBI SimplySAVE SBI Card",
    card_image_url: "/cards/cbi_simplysave_sbi.svg",
    style_classes: "bg-gradient-to-br from-amber-600 to-amber-900 text-amber-50",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_simplyclick_sbi",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "CBI SimplyCLICK SBI Card",
    card_image_url: "/cards/cbi_simplyclick_sbi.svg",
    style_classes: "bg-gradient-to-br from-sky-600 to-blue-700 text-sky-50",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "cbi_rupay_classic",
    bank_id: "central",
    bank_name: "CENTRAL",
    card_name: "Central Bank RuPay Classic",
    card_image_url: "/cards/cbi_rupay_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-500 to-blue-700 text-blue-50",
    apply_url: "https://www.centralbankofindia.co.in/en/credit-card",
  },
  {
    card_id: "uco_rupay_select",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank RuPay Select",
    card_image_url: "/cards/uco_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-blue-950 text-blue-100",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_rupay_platinum",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank RuPay Platinum",
    card_image_url: "/cards/uco_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_visa_signature",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank Visa Signature",
    card_image_url: "/cards/uco_visa_signature.svg",
    style_classes: "bg-gradient-to-br from-slate-800 to-black text-slate-200",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_visa_platinum",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank Visa Platinum",
    card_image_url: "/cards/uco_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-blue-900 text-slate-100",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_visa_gold",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank Visa Gold",
    card_image_url: "/cards/uco_visa_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-500 to-yellow-700 text-yellow-50",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_sbi_elite",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank SBI Card ELITE",
    card_image_url: "/cards/uco_sbi_elite.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-slate-900 text-amber-400",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_sbi_prime",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank SBI Card PRIME",
    card_image_url: "/cards/uco_sbi_prime.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-950 text-blue-100",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_simplysave_sbi",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO SimplySAVE SBI Card",
    card_image_url: "/cards/uco_simplysave_sbi.svg",
    style_classes: "bg-gradient-to-br from-amber-600 to-amber-900 text-amber-50",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_rupay_classic",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank RuPay Classic",
    card_image_url: "/cards/uco_rupay_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-blue-50",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "uco_corporate",
    bank_id: "uco",
    bank_name: "UCO",
    card_name: "UCO Bank Corporate Card",
    card_image_url: "/cards/uco_corporate.svg",
    style_classes: "bg-gradient-to-br from-emerald-700 to-emerald-900 text-emerald-50",
    apply_url: "https://www.ucobank.com/credit-card",
  },
  {
    card_id: "indian_rupay_select",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank RuPay Select",
    card_image_url: "/cards/indian_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-sky-700 to-blue-900 text-sky-50",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_visa_signature",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank Visa Signature",
    card_image_url: "/cards/indian_visa_signature.svg",
    style_classes: "bg-gradient-to-br from-slate-800 to-black text-slate-200",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_mastercard_world",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank Mastercard World",
    card_image_url: "/cards/indian_mastercard_world.svg",
    style_classes: "bg-gradient-to-br from-zinc-800 to-black text-zinc-300",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_rupay_platinum",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank RuPay Platinum",
    card_image_url: "/cards/indian_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_visa_platinum",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank Visa Platinum",
    card_image_url: "/cards/indian_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-900 text-blue-50",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_visa_gold",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank Visa Gold",
    card_image_url: "/cards/indian_visa_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-500 to-yellow-700 text-yellow-50",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_mastercard_titanium",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank Mastercard Titanium",
    card_image_url: "/cards/indian_mastercard_titanium.svg",
    style_classes: "bg-gradient-to-br from-slate-500 to-slate-700 text-slate-100",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_rupay_classic",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank RuPay Classic",
    card_image_url: "/cards/indian_rupay_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-500 to-blue-700 text-blue-50",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_bharat",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank Bharat Card",
    card_image_url: "/cards/indian_bharat.svg",
    style_classes: "bg-gradient-to-br from-orange-500 to-orange-700 text-orange-50",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "indian_corporate",
    bank_id: "indian",
    bank_name: "INDIAN",
    card_name: "Indian Bank Corporate",
    card_image_url: "/cards/indian_corporate.svg",
    style_classes: "bg-gradient-to-br from-emerald-700 to-emerald-900 text-emerald-50",
    apply_url: "https://www.indianbank.in/departments/credit-card/",
  },
  {
    card_id: "bom_rupay_select",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "Bank of Maharashtra RuPay Select",
    card_image_url: "/cards/bom_rupay_select.svg",
    style_classes: "bg-gradient-to-br from-blue-800 to-blue-950 text-blue-100",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_rupay_platinum",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "Bank of Maharashtra RuPay Platinum",
    card_image_url: "/cards/bom_rupay_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-400 to-slate-600 text-slate-900",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_visa_platinum",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "Bank of Maharashtra Visa Platinum",
    card_image_url: "/cards/bom_visa_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-600 to-blue-900 text-slate-100",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_visa_gold",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "Bank of Maharashtra Visa Gold",
    card_image_url: "/cards/bom_visa_gold.svg",
    style_classes: "bg-gradient-to-br from-yellow-500 to-yellow-700 text-yellow-50",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_rupay_classic",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "Bank of Maharashtra RuPay Classic",
    card_image_url: "/cards/bom_rupay_classic.svg",
    style_classes: "bg-gradient-to-br from-blue-600 to-blue-800 text-blue-50",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_maha_sbi_elite",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "MahaBank SBI Card ELITE",
    card_image_url: "/cards/bom_maha_sbi_elite.svg",
    style_classes: "bg-gradient-to-br from-blue-900 to-black text-amber-400",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_maha_sbi_prime",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "MahaBank SBI Card PRIME",
    card_image_url: "/cards/bom_maha_sbi_prime.svg",
    style_classes: "bg-gradient-to-br from-blue-700 to-blue-950 text-blue-100",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_maha_sbi_platinum",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "MahaBank SBI Card Platinum",
    card_image_url: "/cards/bom_maha_sbi_platinum.svg",
    style_classes: "bg-gradient-to-br from-slate-700 to-slate-900 text-slate-300",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_simplysave_sbi",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "MahaBank SimplySAVE SBI Card",
    card_image_url: "/cards/bom_simplysave_sbi.svg",
    style_classes: "bg-gradient-to-br from-amber-600 to-amber-900 text-amber-50",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
  {
    card_id: "bom_corporate",
    bank_id: "bom",
    bank_name: "BOM",
    card_name: "Bank of Maharashtra Corporate",
    card_image_url: "/cards/bom_corporate.svg",
    style_classes: "bg-gradient-to-br from-emerald-600 to-teal-900 text-emerald-50",
    apply_url: "https://www.bankofmaharashtra.in/credit-card",
  },
]

export const CARD_CATALOG: CatalogCard[] = RAW.map((card) => ({
  ...card,
  bank_logo_url: logo(card.bank_id),
  card_image_url: resolveCardImageUrl(card.card_id, card.card_image_url) ?? card.card_image_url,
}))

export function getCatalogCard(cardId: string): CatalogCard | undefined {
  return CARD_CATALOG.find((c) => c.card_id === cardId)
}
