/** Static fallback + source for supabase/indian_airports.sql seeds */
export type IndianAirportRow = {
  iata_code: string
  city: string
  airport_name: string
  state: string
  label: string
}

export const INDIAN_AIRPORTS_SEED: IndianAirportRow[] = [
  { iata_code: "DEL", city: "New Delhi", airport_name: "Indira Gandhi International", state: "Delhi", label: "New Delhi (DEL)" },
  { iata_code: "BOM", city: "Mumbai", airport_name: "Chhatrapati Shivaji Maharaj International", state: "Maharashtra", label: "Mumbai (BOM)" },
  { iata_code: "BLR", city: "Bengaluru", airport_name: "Kempegowda International", state: "Karnataka", label: "Bengaluru (BLR)" },
  { iata_code: "HYD", city: "Hyderabad", airport_name: "Rajiv Gandhi International", state: "Telangana", label: "Hyderabad (HYD)" },
  { iata_code: "MAA", city: "Chennai", airport_name: "Chennai International", state: "Tamil Nadu", label: "Chennai (MAA)" },
  { iata_code: "CCU", city: "Kolkata", airport_name: "Netaji Subhas Chandra Bose International", state: "West Bengal", label: "Kolkata (CCU)" },
  { iata_code: "GOI", city: "Goa", airport_name: "Manohar International", state: "Goa", label: "Goa (GOI)" },
  { iata_code: "GOX", city: "Goa", airport_name: "Dabolim International", state: "Goa", label: "Goa Dabolim (GOX)" },
  { iata_code: "PNQ", city: "Pune", airport_name: "Pune International", state: "Maharashtra", label: "Pune (PNQ)" },
  { iata_code: "AMD", city: "Ahmedabad", airport_name: "Sardar Vallabhbhai Patel International", state: "Gujarat", label: "Ahmedabad (AMD)" },
  { iata_code: "COK", city: "Kochi", airport_name: "Cochin International", state: "Kerala", label: "Kochi (COK)" },
  { iata_code: "TRV", city: "Thiruvananthapuram", airport_name: "Trivandrum International", state: "Kerala", label: "Thiruvananthapuram (TRV)" },
  { iata_code: "CCJ", city: "Kozhikode", airport_name: "Calicut International", state: "Kerala", label: "Kozhikode (CCJ)" },
  { iata_code: "CNN", city: "Kannur", airport_name: "Kannur International", state: "Kerala", label: "Kannur (CNN)" },
  { iata_code: "JAI", city: "Jaipur", airport_name: "Jaipur International", state: "Rajasthan", label: "Jaipur (JAI)" },
  { iata_code: "UDR", city: "Udaipur", airport_name: "Maharana Pratap", state: "Rajasthan", label: "Udaipur (UDR)" },
  { iata_code: "JDH", city: "Jodhpur", airport_name: "Jodhpur", state: "Rajasthan", label: "Jodhpur (JDH)" },
  { iata_code: "LKO", city: "Lucknow", airport_name: "Chaudhary Charan Singh International", state: "Uttar Pradesh", label: "Lucknow (LKO)" },
  { iata_code: "VNS", city: "Varanasi", airport_name: "Lal Bahadur Shastri International", state: "Uttar Pradesh", label: "Varanasi (VNS)" },
  { iata_code: "AGR", city: "Agra", airport_name: "Agra", state: "Uttar Pradesh", label: "Agra (AGR)" },
  { iata_code: "IXC", city: "Chandigarh", airport_name: "Chandigarh International", state: "Chandigarh", label: "Chandigarh (IXC)" },
  { iata_code: "ATQ", city: "Amritsar", airport_name: "Sri Guru Ram Dass Jee International", state: "Punjab", label: "Amritsar (ATQ)" },
  { iata_code: "IXJ", city: "Jammu", airport_name: "Jammu", state: "Jammu and Kashmir", label: "Jammu (IXJ)" },
  { iata_code: "SXR", city: "Srinagar", airport_name: "Sheikh ul-Alam International", state: "Jammu and Kashmir", label: "Srinagar (SXR)" },
  { iata_code: "IXL", city: "Leh", airport_name: "Kushok Bakula Rimpochee", state: "Ladakh", label: "Leh (IXL)" },
  { iata_code: "DED", city: "Dehradun", airport_name: "Jolly Grant", state: "Uttarakhand", label: "Dehradun (DED)" },
  { iata_code: "GAU", city: "Guwahati", airport_name: "Lokpriya Gopinath Bordoloi International", state: "Assam", label: "Guwahati (GAU)" },
  { iata_code: "IXB", city: "Bagdogra", airport_name: "Bagdogra", state: "West Bengal", label: "Bagdogra (IXB)" },
  { iata_code: "IXR", city: "Ranchi", airport_name: "Birsa Munda", state: "Jharkhand", label: "Ranchi (IXR)" },
  { iata_code: "PAT", city: "Patna", airport_name: "Jay Prakash Narayan International", state: "Bihar", label: "Patna (PAT)" },
  { iata_code: "GAY", city: "Gaya", airport_name: "Gaya", state: "Bihar", label: "Gaya (GAY)" },
  { iata_code: "BBI", city: "Bhubaneswar", airport_name: "Biju Patnaik International", state: "Odisha", label: "Bhubaneswar (BBI)" },
  { iata_code: "VTZ", city: "Visakhapatnam", airport_name: "Visakhapatnam", state: "Andhra Pradesh", label: "Visakhapatnam (VTZ)" },
  { iata_code: "RJA", city: "Rajahmundry", airport_name: "Rajahmundry", state: "Andhra Pradesh", label: "Rajahmundry (RJA)" },
  { iata_code: "TIR", city: "Tirupati", airport_name: "Tirupati", state: "Andhra Pradesh", label: "Tirupati (TIR)" },
  { iata_code: "VGA", city: "Vijayawada", airport_name: "Vijayawada", state: "Andhra Pradesh", label: "Vijayawada (VGA)" },
  { iata_code: "IXZ", city: "Port Blair", airport_name: "Veer Savarkar International", state: "Andaman and Nicobar", label: "Port Blair (IXZ)" },
  { iata_code: "NAG", city: "Nagpur", airport_name: "Dr. Babasaheb Ambedkar International", state: "Maharashtra", label: "Nagpur (NAG)" },
  { iata_code: "IDR", city: "Indore", airport_name: "Devi Ahilya Bai Holkar", state: "Madhya Pradesh", label: "Indore (IDR)" },
  { iata_code: "BHO", city: "Bhopal", airport_name: "Raja Bhoj", state: "Madhya Pradesh", label: "Bhopal (BHO)" },
  { iata_code: "JLR", city: "Jabalpur", airport_name: "Jabalpur", state: "Madhya Pradesh", label: "Jabalpur (JLR)" },
  { iata_code: "RPR", city: "Raipur", airport_name: "Swami Vivekananda", state: "Chhattisgarh", label: "Raipur (RPR)" },
  { iata_code: "IXE", city: "Mangaluru", airport_name: "Mangalore International", state: "Karnataka", label: "Mangaluru (IXE)" },
  { iata_code: "HBX", city: "Hubballi", airport_name: "Hubballi", state: "Karnataka", label: "Hubballi (HBX)" },
  { iata_code: "IXG", city: "Belagavi", airport_name: "Belagavi", state: "Karnataka", label: "Belagavi (IXG)" },
  { iata_code: "MYQ", city: "Mysuru", airport_name: "Mysuru", state: "Karnataka", label: "Mysuru (MYQ)" },
  { iata_code: "BDQ", city: "Vadodara", airport_name: "Vadodara", state: "Gujarat", label: "Vadodara (BDQ)" },
  { iata_code: "STV", city: "Surat", airport_name: "Surat", state: "Gujarat", label: "Surat (STV)" },
  { iata_code: "RAJ", city: "Rajkot", airport_name: "Rajkot", state: "Gujarat", label: "Rajkot (RAJ)" },
  { iata_code: "BHU", city: "Bhavnagar", airport_name: "Bhavnagar", state: "Gujarat", label: "Bhavnagar (BHU)" },
  { iata_code: "IXU", city: "Aurangabad", airport_name: "Aurangabad", state: "Maharashtra", label: "Aurangabad (IXU)" },
  { iata_code: "NMI", city: "Nashik", airport_name: "Nashik", state: "Maharashtra", label: "Nashik (NMI)" },
  { iata_code: "KLH", city: "Kolhapur", airport_name: "Kolhapur", state: "Maharashtra", label: "Kolhapur (KLH)" },
  { iata_code: "IXM", city: "Madurai", airport_name: "Madurai", state: "Tamil Nadu", label: "Madurai (IXM)" },
  { iata_code: "TRZ", city: "Tiruchirappalli", airport_name: "Tiruchirappalli International", state: "Tamil Nadu", label: "Tiruchirappalli (TRZ)" },
  { iata_code: "CJB", city: "Coimbatore", airport_name: "Coimbatore International", state: "Tamil Nadu", label: "Coimbatore (CJB)" },
  { iata_code: "SXV", city: "Salem", airport_name: "Salem", state: "Tamil Nadu", label: "Salem (SXV)" },
  { iata_code: "TCR", city: "Tuticorin", airport_name: "Tuticorin", state: "Tamil Nadu", label: "Tuticorin (TCR)" },
  { iata_code: "IMF", city: "Imphal", airport_name: "Imphal", state: "Manipur", label: "Imphal (IMF)" },
  { iata_code: "AJL", city: "Aizawl", airport_name: "Lengpui", state: "Mizoram", label: "Aizawl (AJL)" },
  { iata_code: "SHL", city: "Shillong", airport_name: "Shillong", state: "Meghalaya", label: "Shillong (SHL)" },
  { iata_code: "DMU", city: "Dimapur", airport_name: "Dimapur", state: "Nagaland", label: "Dimapur (DMU)" },
  { iata_code: "IXA", city: "Agartala", airport_name: "Maharaja Bir Bikram", state: "Tripura", label: "Agartala (IXA)" },
  { iata_code: "DIB", city: "Dibrugarh", airport_name: "Dibrugarh", state: "Assam", label: "Dibrugarh (DIB)" },
  { iata_code: "IXS", city: "Silchar", airport_name: "Silchar", state: "Assam", label: "Silchar (IXS)" },
  { iata_code: "TEZ", city: "Tezpur", airport_name: "Tezpur", state: "Assam", label: "Tezpur (TEZ)" },
  { iata_code: "JRH", city: "Jorhat", airport_name: "Jorhat", state: "Assam", label: "Jorhat (JRH)" },
  { iata_code: "IXD", city: "Allahabad", airport_name: "Prayagraj", state: "Uttar Pradesh", label: "Prayagraj (IXD)" },
  { iata_code: "GOP", city: "Gorakhpur", airport_name: "Gorakhpur", state: "Uttar Pradesh", label: "Gorakhpur (GOP)" },
  { iata_code: "KNU", city: "Kanpur", airport_name: "Kanpur", state: "Uttar Pradesh", label: "Kanpur (KNU)" },
  { iata_code: "IXW", city: "Jamshedpur", airport_name: "Sonari", state: "Jharkhand", label: "Jamshedpur (IXW)" },
  { iata_code: "DBR", city: "Darbhanga", airport_name: "Darbhanga", state: "Bihar", label: "Darbhanga (DBR)" },
  { iata_code: "IXI", city: "Lilabari", airport_name: "Lilabari", state: "Assam", label: "Lilabari (IXI)" },
  { iata_code: "SLV", city: "Shimla", airport_name: "Shimla", state: "Himachal Pradesh", label: "Shimla (SLV)" },
  { iata_code: "KUU", city: "Kullu", airport_name: "Bhuntar", state: "Himachal Pradesh", label: "Kullu (KUU)" },
  { iata_code: "DHM", city: "Dharamshala", airport_name: "Gaggal", state: "Himachal Pradesh", label: "Dharamshala (DHM)" },
  { iata_code: "PGH", city: "Pantnagar", airport_name: "Pantnagar", state: "Uttarakhand", label: "Pantnagar (PGH)" },
  { iata_code: "DIU", city: "Diu", airport_name: "Diu", state: "Daman and Diu", label: "Diu (DIU)" },
  { iata_code: "ISK", city: "Nashik", airport_name: "Ozar", state: "Maharashtra", label: "Nashik Ozar (ISK)" },
  { iata_code: "SAG", city: "Shirdi", airport_name: "Shirdi", state: "Maharashtra", label: "Shirdi (SAG)" },
  { iata_code: "JGA", city: "Jamnagar", airport_name: "Jamnagar", state: "Gujarat", label: "Jamnagar (JGA)" },
  { iata_code: "BKB", city: "Bikaner", airport_name: "Nal", state: "Rajasthan", label: "Bikaner (BKB)" },
  { iata_code: "KQH", city: "Kishangarh", airport_name: "Kishangarh", state: "Rajasthan", label: "Kishangarh (KQH)" },
  { iata_code: "HSR", city: "Rajkot", airport_name: "Hirasar", state: "Gujarat", label: "Rajkot Hirasar (HSR)" },
  { iata_code: "PYG", city: "Gangtok", airport_name: "Pakyong", state: "Sikkim", label: "Gangtok (PYG)" },
  { iata_code: "IXH", city: "Kailashahar", airport_name: "Kailashahar", state: "Tripura", label: "Kailashahar (IXH)" },
  { iata_code: "RDP", city: "Durgapur", airport_name: "Kazi Nazrul Islam", state: "West Bengal", label: "Durgapur (RDP)" },
  { iata_code: "CDP", city: "Kadapa", airport_name: "Kadapa", state: "Andhra Pradesh", label: "Kadapa (CDP)" },
  { iata_code: "PUT", city: "Puttaparthi", airport_name: "Sri Sathya Sai", state: "Andhra Pradesh", label: "Puttaparthi (PUT)" },
  { iata_code: "BEP", city: "Bellary", airport_name: "Ballari", state: "Karnataka", label: "Bellary (BEP)" },
  { iata_code: "VDY", city: "Vidyanagar", airport_name: "Jindal Vijaynagar", state: "Karnataka", label: "Vidyanagar (VDY)" },
  { iata_code: "BUP", city: "Bathinda", airport_name: "Bathinda", state: "Punjab", label: "Bathinda (BUP)" },
  { iata_code: "LUH", city: "Ludhiana", airport_name: "Ludhiana", state: "Punjab", label: "Ludhiana (LUH)" },
  { iata_code: "DHN", city: "Dhanbad", airport_name: "Dhanbad", state: "Jharkhand", label: "Dhanbad (DHN)" },
  { iata_code: "BHJ", city: "Bhuj", airport_name: "Bhuj", state: "Gujarat", label: "Bhuj (BHJ)" },
  { iata_code: "JGB", city: "Jagdalpur", airport_name: "Jagdalpur", state: "Chhattisgarh", label: "Jagdalpur (JGB)" },
  { iata_code: "JSA", city: "Jaisalmer", airport_name: "Jaisalmer", state: "Rajasthan", label: "Jaisalmer (JSA)" },
  { iata_code: "HGI", city: "Itanagar", airport_name: "Hollongi", state: "Arunachal Pradesh", label: "Itanagar (HGI)" },
  { iata_code: "TEI", city: "Tezu", airport_name: "Tezu", state: "Arunachal Pradesh", label: "Tezu (TEI)" },
  { iata_code: "ZER", city: "Ziro", airport_name: "Ziro", state: "Arunachal Pradesh", label: "Ziro (ZER)" },
  { iata_code: "PBD", city: "Porbandar", airport_name: "Porbandar", state: "Gujarat", label: "Porbandar (PBD)" },
  { iata_code: "IXY", city: "Kandla", airport_name: "Kandla", state: "Gujarat", label: "Kandla (IXY)" },
  { iata_code: "IXK", city: "Keshod", airport_name: "Keshod", state: "Gujarat", label: "Keshod (IXK)" },
]

/** UI-friendly shape (matches legacy INDIAN_AIRPORTS in flight-search) */
export function toAirportOption(row: IndianAirportRow) {
  return {
    code: row.iata_code,
    city: row.city,
    label: row.label,
    airportName: row.airport_name,
    state: row.state,
  }
}

export const FALLBACK_AIRPORT_OPTIONS = INDIAN_AIRPORTS_SEED.map(toAirportOption)
