/** @deprecated Import from `@/lib/affiliate-links` — re-exports for compatibility */
export {
  AFFILIATE_MARKERS,
  wrapTravelpayoutsClick,
  wrapAmazonProductUrl,
  wrapFlipkartProductUrl,
  formatDateDdMmYyyy,
  buildMakeMyTripFlightUrl,
  buildCleartripFlightUrl,
  buildGoibiboFlightUrl,
  buildMakeMyTripHotelUrl,
  buildBookingHotelUrl,
  buildAgodaHotelUrl,
  buildFlightAffiliateLinks,
  buildHotelAffiliateLinks,
  buildProductAffiliateLinks,
  primaryAffiliateBookLabel,
  primaryAffiliateBookLabel as primaryTravelBookLabel,
  type AffiliateLink,
  type AffiliateLink as TravelAffiliateLink,
  type AffiliatePartner,
  type AffiliatePartner as TravelOtaPartner,
} from "@/lib/affiliate-links"
